### ISSUE TITLE
m tools to install rust toolchain failed, when prepare the compilation environment.

### ISSUE THREAD

**Issue by jeffliuyue** [AmbiML/sparrow-cantrip-full#2]
following the GettingStarted.md step by step.
... ...
$ export PLATFORM=rpi3
$ source build/setup.sh
ROOTDIR=/home/jeff/SEL4/sparrow/cantripOS
OUT=/home/jeff/SEL4/sparrow/cantripOS/out
PLATFORM=sparrow

Type 'm [target]' to build.

Targets available are:

Usage: hmm [-h] [-l] <targetname>

To get more information on a target, use 'hmm [target]'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
You have missing tools. Please run 'm prereqs' followed
by 'm tools' to install them.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

/home/jeff/SEL4/sparrow/cantripOS/cache/toolchain is missing
/home/jeff/SEL4/sparrow/cantripOS/cache/toolchain_iree_rv32imf is missing!
$ m tools
...
Failed to execute 'wget --progress=dot:giga -O /home/jeff/SEL4/sparrow/cantripOS/out/rust_toolchain_latest.tar.xz https://storage.googleapis.com/sparrow-public-artifacts/rust_toolchain_latest.tar.xz': exited with return code 8
....
**and Access this url(https://storage.googleapis.com/sparrow-public-artifacts/rust_toolchain_latest.tar.xz) through a browser and find that this file does not exist, so I doubt the correctness of this url.
in ./scripts/fetch-rust-toolchain.sh;
PUBLIC_ARTIFACTS_URL="https://storage.googleapis.com/sparrow-public-artifacts"**

**Comment by Arthasczt** [comment]
I found this same problem two. Can someone help us?

**Comment by sleffler** [comment]
"m tools" is only for our internal use (we stage the toolchain & mirror
public crates for building the sparrow platform).

Please follow the documentation.
