### ISSUE TITLE
About a cantrip-shell question

### ISSUE THREAD

**Issue by 9Back833** [AmbiML/sparrow-cantrip-full#4]
When I run :
`m simulate-debug`

The shell displays the following：
```
CANTRIP> EOF
cantrip_memory_manager::Global memory: 0 allocated 124436224 free, reserved: 2334720 kernel 7405568 user
```

I want to run the correct shell.
I appreciate any guidance you could share:)

**Comment by sleffler** [comment]
Your target platform appears to lack a uart driver. If this is a raspi
there is no driver atm; someone will need to step up and write one. In the
meantime you can put shell commands in the autostart.repl
<https://github.com/AmbiML/sparrow-cantrip-full/blob/main/apps/repl/autostart.repl>
 file.

**Comment by 9Back833** [comment]
First of all, thank you for your reply.

For the first solution, I built an experimental environment based on the process of _GettingStarted.md_, using a qemu simulator. But，_EOF_ will appear in the shell.

For the second solution, I try to put shell commands in the autostart.repl. But the result is still disappointing, and _EOF_ still appears.

I hope you can share how to run the shell correctly.
I would appreciate your sharing:)

**Comment by jeffliuyue** [comment]
I have the same question. Since this project has been pushed to github, we expect to get complete and accurate project information and content, and to be able to synchronize to the latest update in time.

**Comment by sleffler** [comment]
Latest updates run multiple applications from autostart.repl on rpi3.
