### ISSUE TITLE
Is it possible to build a riscv version of cantripos?

### ISSUE THREAD

**Issue by zqyzsj** [AmbiML/sparrow-cantrip-full#5]
Although the get started says that the current version of cantripOS only supports pi3, I notice that in the build directory, there is a sparrow configuration (cantrip_build/build/platforms$), which is riscv32 architecture.  So is it possible to build a riscv version of cantripOS? If it is possible, can anybody give some suggestions?
And another question, is it possible to build a riscv64 version of cantripOS? If possible, any suggestions?

Thanks.

**Comment by sleffler** [comment]
The issue w/ riscv (32- or 64-bit) is that the kernel was forked and the
upstream riscv support was gutted. So booting it on a non-sparrow system
requires re-merging upstream's support. This is on our TODO list but low
priority. If you were to do this work we'd gladly integrate it.

**Comment by zqyzsj** [comment]
> 

Yes, we are planning to port cantripOS to a risv64 CPU. 
I find that some kernel services only support riscv32 (such as sel4bundle). So we currently are not clear on what to do if we want to run cantripOS on a riscv64 CPU.

We would be well appreciated if you give us some guidance or steps about how to port it to a different archtecture.

Thanks.

**Comment by sleffler** [comment]
I suggest you get stock seL4 working on your target platform. Then merge
any kernel differences related to the platform into the (forked)
sparrow-kernel code. I would be surprised if anything that runs in user
space needs to be modified.

Note our riscv platform does not use sbi. I believe I made this an
attribute of the platform but w/o testing on a platform that requires
opensbi/sbi it's possible you may need to fixup something in this area.
