### ISSUE TITLE
Relocation error occurred in cross compilation

### ISSUE THREAD

**Issue by BruceZhang5337** [AmbiML/sparrow-cantrip-full#7]
hi ,i am Bruce. when i get started with repo & the build system, i perform ' m simulate-debug', and get the error as followed.
229/328] Linking C executable process_manager.instance.bin
FAILED: process_manager.instance.bin 
: && /usr/bin/ccache /home/zzw/arm-gnu-toolchain/bin/aarch64-none-linux-gnu-gcc --sysroot=/home/zzw/sparrow/out/cantrip/aarch64-unknown-elf/debug  -march=armv8-a+crc   -D__KERNEL_64__  -D__KERNEL_64__   -static -nostdlib -z max-page-size=0x1000    -static -nostdlib -u _camkes_start -e _camkes_start  -Wl,--script=/home/zzw/sparrow/out/cantrip/aarch64-unknown-elf/debug/process_manager/linker.lds   -Wl,-umuslcsys_init_muslc /home/zzw/sparrow/out/cantrip/aarch64-unknown-elf/debug/lib/crt0.o /home/zzw/sparrow/out/cantrip/aarch64-unknown-elf/debug/lib/crti.o /home/zzw/arm-gnu-toolchain/bin/../lib/gcc/aarch64-none-linux-gnu/12.2.1/crtbegin.o CMakeFiles/process_manager.instance.bin.dir/process_manager/camkes.c.obj CMakeFiles/process_manager.instance.bin.dir/process_manager/camkes.environment.c.obj CMakeFiles/process_manager.instance.bin.dir/process_manager/proc_ctrl_seL4RPCCall_0.c.obj CMakeFiles/process_manager.instance.bin.dir/process_manager/sdk_manager_seL4RPCCall_0.c.obj CMakeFiles/process_manager.instance.bin.dir/process_manager/pkg_mgmt_seL4RPCOverMultiSharedData_0.c.obj CMakeFiles/process_manager.instance.bin.dir/process_manager/memory_seL4RPCOverMultiSharedData_1.c.obj CMakeFiles/process_manager.instance.bin.dir/process_manager/security_seL4RPCOverMultiSharedData_1.c.obj CMakeFiles/process_manager.instance.bin.dir/process_manager/logger_seL4RPCOverMultiSharedData_0.c.obj CMakeFiles/process_manager.instance.bin.dir/process_manager/camkes.cantripos.c.obj -Wl,--start-group         -lgcc -lgcc_eh  libsel4/libsel4.a  sel4runtime/libsel4runtime.a  camkes-tool/libsel4camkes/libsel4camkes.a  seL4_libs/libsel4sync/libsel4sync.a  util_libs/libutils/libutils.a  seL4_libs/libsel4vka/libsel4vka.a  seL4_libs/libsel4utils/libsel4utils.a  seL4_libs/libsel4bench/libsel4bench.a  seL4_libs/libsel4platsupport/libsel4platsupport.a  util_libs/libplatsupport/libplatsupport.a  seL4_libs/libsel4vspace/libsel4vspace.a  seL4_libs/libsel4muslcsys/libsel4muslcsys.a  libcantrip_process_manager.a  seL4_libs/libsel4utils/libsel4utils.a  seL4_libs/libsel4platsupport/libsel4platsupport.a  sel4runtime/libsel4runtime.a  util_libs/libplatsupport/libplatsupport.a  util_libs/libfdt/libfdt.a  -Wl,--undefined=arm_gic_ptr,--undefined=tegra_ictlr_ptr,--undefined=arm_gicv3_ptr,--undefined=fsl_avic_ptr,--undefined=ti_omap3_ptr  seL4_libs/libsel4simple-default/libsel4simple-default.a  seL4_libs/libsel4vspace/libsel4vspace.a  seL4_libs/libsel4simple/libsel4simple.a  seL4_libs/libsel4vka/libsel4vka.a  util_libs/libelf/libelf.a  util_libs/libcpio/libcpio.a  -Wl,-u -Wl,__vsyscall_ptr  seL4_libs/libsel4debug/libsel4debug.a  projects_libs/libvirtqueue/libvirtqueue.a  libsel4/libsel4.a  util_libs/libutils/libutils.a  musllibc/build-temp/stage/lib/libc.a -Wl,--end-group /home/zzw/arm-gnu-toolchain/bin/../lib/gcc/aarch64-none-linux-gnu/12.2.1/crtend.o /home/zzw/sparrow/out/cantrip/aarch64-unknown-elf/debug/lib/crtn.o -o process_manager.instance.bin && :
/home/zzw/arm-gnu-toolchain/bin/../lib/gcc/aarch64-none-linux-gnu/12.2.1/../../../../aarch64-none-linux-gnu/bin/ld: musllibc/build-temp/stage/lib/libc.a(__stdio_exit.o): copy relocation against non-copyable protected symbol `__stdin_used'

**Comment by BruceZhang5337** [comment]
I install latest' aarch64-none-linux-gnu 'from https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads, which is the reason for the debug?  the version doesn't meet the requirement?

**Comment by BruceZhang5337** [comment]
I solved this problem by installing an older toolchain!!

**Comment by BruceZhang5337** [comment]
However, when the image file was generated at the end of the execution, the following error occurred.
images/capdl-loader-image-arm-bcm2837 
cd /home/zzw/sparrow/out/cantrip/aarch64-unknown-elf/debug && /usr/bin/objcopy -O binary /home/zzw/sparrow/out/cantrip/aarch64-unknown-elf/debug/elfloader/elfloader /home/zzw/sparrow/out/cantrip/aarch64-unknown-elf/debug/images/capdl-loader-image-arm-bcm2837
/usr/bin/objcopy: Unable to recognise the format of the input file `/home/zzw/sparrow/out/cantrip/aarch64-unknown-elf/debug/elfloader/elfloader'

**Comment by BruceZhang5337** [comment]
one more question: qemu-system-aarch64: -machine raspi3b: unsupported machine type 'raspi3b'
Use -machine help to list supported machines,and i got the result that included raspi2 and raspi3. 
I'm confused. I  installed qemu-system-aarch64 only. Do i need to install something else？

**Comment by BruceZhang5337** [comment]
how can i get to the cantrip console? i do 'm simulator' and  get some information 'CANTRIP>EOF'. I don't know how to use the cantrip console.

**Comment by sleffler** [comment]
Not sure why your qemu-system-aarch64 does not like the raspi3b image
unless it somehow got built with -DAARC64=0 (so 32-bit instead of 64-bit).
My qemu comes from an internal pre-built so am not sure how it was
configured:

$ qemu-system-aarch64 --version
QEMU emulator version 7.2.0 (Debian 1:7.2+dfsg-1+build1)
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

You might get a more informed answer on the devel@ mailing list.

As to how to get a console; the sparrow-cantrip-full docs call out there is
no interactive console because there is no UART driver. I stick commands in
autostart.repl so they are automatically run at boot. But beware that atm
applications do not work correctly--I hope to push updates to GH this week
that fix that.

**Comment by BruceZhang5337** [comment]
thanks a lot for your reply. I solved the problem of 'qemu-system-aarch64' by replacing another version ,exactly the latest version. Looking forward to the launch of interactive console! :) 
best wishes!
